version: '2.0'
services:
  web:
    build: .
    env_file: .env
    environment:
      - PORT=${PORT}
    working_dir: /app/user
    ports:
      - '${PORT}:${PORT}'

  shell:
    build: .
    working_dir: /app/user
    environment:
      PORT: 8080
    ports:
      - '8080:8080'
    volumes:
      - '.:/app/user'
