<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FiscalYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiscalYearRepository extends EntityRepository
{

}
